name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # Snake Animation
      - name: Snake Animation
        id: snake-gif
        run: |
          echo "github_user_name=marceloamellopaixao" >> $GITHUB_ENV
          echo "svg_out_path=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV
          npx snk

      # Setando as variáveis de ambiente para serem usadas em etapas posteriores
      - name: Set Environment Variables
        run: echo "MY_OUTPUT_VAR=123" >> $GITHUB_ENV

      # Criar uma nova tag para a versão
      - name: Criar Tag de Versão
        run: git tag v1.0
        if: success()  # Executar apenas se os passos anteriores forem bem-sucedidos

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-release@v2
        with:
          draft: false
          prerelease: false
          repository: ${{ github.repository }}
          tag_name: v1.0
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_OUTPUT_VAR: ${{ env.MY_OUTPUT_VAR }}
        if: success()  # Executar apenas se os passos anteriores forem bem-sucedidos
