name: Snake Git

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      # Snake Animation
      - name: Snake Animation
        id: snake-gif
        run: |
          echo "github_user_name=betafontes" >> $GITHUB_ENV
          echo "svg_out_path=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV
          npx snk

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
