name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      # Snake Animation
      - name: Snake Animation
        id: snake-gif
        run: |
          echo "github_user_name=marceloamellopaixao" >> $GITHUB_ENV
          echo "svg_out_path=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV
          npx snk

      # Setando as variáveis de ambiente para serem usadas em etapas posteriores
      - name: Set Environment Variables
        run: echo "MY_OUTPUT_VAR=123" >> $GITHUB_ENV

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_OUTPUT_VAR: ${{ env.MY_OUTPUT_VAR }}
        if: success()  # Executar apenas se os passos anteriores forem bem-sucedidos
